name: "telegram_bot"
version: "0.6.2"
lang: "en"
timezone: "Europe/Paris"
antiflood:
  enabled: true
  time_window_seconds: 2
apps:
  - menu
  - llm
  - google_drive
  - google_sheets
  - item
  - start
db:
  name: "telegram_bot"
  tables:
    - users
    - events