name: "telegram_bot"
version: "0.5.0"
lang: "en"
timezone: "Europe/Paris"
antiflood:
  enabled: true
  time_window_seconds: 2
apps:
  - menu
  - llm
  - google_drive
  - resource
db:
  name: "telegram_bot"
  tables:
    - users
    - events